### ISSUE TITLE
 Regarding 1.06b

### ISSUE THREAD

**Issue by RaSSta** [fearedbliss/singling#1]
There seems to be a bug where my character is invisible. Tried to join a TCP/IP game, and it said "Failed to join game" and my character on the character screen is that of a man with a beard in a brown robe... The game seems to not be detecting my character.. but when i click on the stash and inventory everything is there and fine. I have my chars backed up, might have to reinstall? Thanks for your efforts, no CD would be great and this is the closest solution i have found. Thanks for your efforts!

**Comment by fearedbliss** [comment]
Does this issue have in regular 1.06b? It might be something weird with the repacked . exe. I didn't create these but simply included them from GalaxyHaxz in my add-on pack. I won't be able to fix this issue other than repackaging a new . exe if he has one.
